apiVersion: batch/v1
kind: CronJob
metadata:
  name: job-scheduler
  namespace: senegalservices
spec:
  schedule: "0 2 * * *"  # Tous les jours à 2h
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: job-scheduler
            image: senegalservices/auth-service:latest
            command: ["node"]
            args: ["dist/scripts/schedule-jobs.js"]
            env:
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: JOB_TYPE
              value: "avatar-refresh"